# Generated by Django 2.2.7 on 2019-11-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferred_cateogies',
            new_name='preferred_categories',
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_max_limit',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_max_limit',
            field=models.IntegerField(default=5000),
        ),
    ]
