# Generated by Django 2.2.7 on 2019-11-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz',
            field=models.CharField(default='Asia/Kolkata', max_length=40),
        ),
    ]
